config/routes.rb
Rails.application.routes.draw do
  resources :paintings
  root 'paintings#index'

end

app/models/painting.rb
class Painting < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]

  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paintings }
    end
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @painting }
    end
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = Painting.new(painting_params)

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render json: @painting, status: :created }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:name, :image, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_381_file_upload

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/paintings/_form.html.haml
= simple_form_for(@painting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :image, as: :file
    = f.input :remote_image_url, as: :string

  .form-actions
    = f.button :submit

app/views/paintings/_painting.html.haml
.col-sm-3
  %h3= painting.name
  %p
    = link_to painting do
      = image_tag painting.image_url(:thumb)
  %p
    = link_to 'Show', painting
    = link_to 'Edit', edit_painting_path(painting)
    = link_to 'Destroy', painting, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/paintings/edit.html.haml
.page-header
  = link_to paintings_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @painting, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing painting

= render 'form'

app/views/paintings/index.html.haml
.page-header
  = link_to new_painting_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Painting
  %h1 Listing paintings

= simple_form_for Painting.new do |f|
  = f.input :image, as: :file, input_html:{multiple:true, id:'new_paintings', name:'painting[image]'}

-#%p
-#  = form_for Painting.new do |f|
-#    = f.file_field :image, id:'new_paintings', multiple:true, name:'painting[image]'

#paintings
  = render @paintings

-#.table-responsive
-#  %table.table.table-striped.table-bordered.table-hover
-#    %thead
-#      %tr
-#        %th Name
-#        %th Image
-#        %th
-#        %th
-#        %th
-#
-#    %tbody
-#      - @paintings.each do |painting|
-#        %tr
-#          %td= painting.name
-#          %td= painting.image
-#          %td= link_to 'Show', painting
-#          %td= link_to 'Edit', edit_painting_path(painting)
-#          %td= link_to 'Destroy', painting, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/paintings/new.html.haml
.page-header
  = link_to paintings_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New painting

= render 'form'

app/views/paintings/show.html.haml
.page-header
  = link_to paintings_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_painting_path(@painting), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show painting

%dl.dl-horizontal
  %dt Name:
  %dd= @painting.name
  %dt Image:
  %dd= image_tag @painting.image_url